server:
  port: ${SERVER_PORT}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${GIT_CONFIGS_URL}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          clone-on-start: true
          default-label: master